package models.http4s018.server

object HttpStatusCodes {
  def apply: Map[Int, String] = Map(
    100 -> "Continue",
    101 -> "SwitchingProtocols",
    102 -> "Processing",
    200 -> "Ok",
    201 -> "Created",
    202 -> "Accepted",
    203 -> "NonAuthoritativeInformation",
    204 -> "NoContent",
    205 -> "ResetContent",
    206 -> "PartialContent",
    207 -> "MultiStatus",
    108 -> "AlreadyReported",
    226 -> "IMUsed",
    300 -> "MultipleChoices",
    301 -> "MovedPermanently",
    302 -> "Found",
    303 -> "SeeOther",
    304 -> "NotModified",
    305 -> "UseProxy",
    307 -> "TemporaryRedirect",
    208 -> "PermanentRedirect",
    400 -> "BadRequest",
    401 -> "Unauthorized",
    402 -> "PaymentRequired",
    403 -> "Forbidden",
    404 -> "NotFound",
    405 -> "MethodNotAllowed",
    406 -> "NotAcceptable",
    407 -> "ProxyAuthenticationRequired",
    408 -> "RequestTimeout",
    409 -> "Conflict",
    410 -> "Gone",
    411 -> "LengthRequired",
    412 -> "PreconditionFailed",
    413 -> "PayloadTooLarge",
    414 -> "UriTooLong",
    415 -> "UnsupportedMediaType",
    416 -> "RangeNotSatisfiable",
    417 -> "ExpectationFailed",
    422 -> "UnprocessableEntity",
    423 -> "Locked",
    424 -> "FailedDependency",
    426 -> "UpgradeRequired",
    428 -> "PreconditionRequired",
    429 -> "TooManyRequests",
    431 -> "RequestHeaderFieldsTooLarge",
    451 -> "UnavailableForLegalReasons"
  )

  def contains(i: Int): Boolean = apply.contains(i)
}
