package testUtils

import examples.MurmurRandomStringGenerator
import generator.PostmanCollectionGenerator

object TestPostmanCollectionGenerator extends PostmanCollectionGenerator(MurmurRandomStringGenerator)
