package scala.models

import org.scalatest.{ShouldMatchers, FunSpec}

class ApidocCommentsSpec extends FunSpec with ShouldMatchers {

  it("with only version") {
    ApidocComments("1.0", None).toJavaString should be("""
/**
 * Generated by API Builder - https://www.apibuilder.io
 * Service version: 1.0
 */
""".trim)

    ApidocComments("1.0", None).forPlayRoutes should be("""
# Generated by API Builder - https://www.apibuilder.io
# Service version: 1.0
""".trim)
  }

}
