package lib

class AbstractApiBuilderComments(val version: String, val userAgent: Option[String]) {

  val elements: Seq[String] = Seq(
    Some(s"Generated by API Builder - ${Constants.ApiBuilderUrl}"),
    Some(s"Service version: ${version}"),
    userAgent.map { a => s"User agent: $a" }
  ).flatten

}