package scala.models

import scala.generator.ScalaUtil
import lib.Constants

/**
  * @param version e.g. 1.2.3 Used to inject headers on the full version and the major version number
  */
case class ApiBuilderComments(version: String, userAgent: Option[String]) {

  def toJavaString: String = ScalaUtil.textToComment(elements)

  def forPlayRoutes: String = elements.map(s => s"# $s").mkString("\n")

  private[this] val elements = Seq(
    Some(s"Generated by API Builder - ${Constants.ApiBuilderUrl}"),
    Some(s"Service version: $version"),
    userAgent
  ).flatten

}
